version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
      - ./nginx-logs:/var/log/nginx
      - ./web-root:/var/www/html
      - ./dhparam:/etc/ssl/certs
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    ports:
      - "80:50080"
      - "443:50443"
    networks:
      - app-network
    restart: unless-stopped

  certbot:
    image: certbot/dns-cloudflare
    container_name: certbot
    volumes:
      - ./web-root:/var/www/html
      - ./cloudflare.ini:/etc/cloudflare/credentials.ini
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    networks:
      - app-network
    depends_on:
      - nginx
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/credentials.ini --noninteractive --email v.d.sobolev@ya.ru --agree-tos --no-eff-email --staging -d vdsobolev.ru -d *.vdsobolev.ru

volumes:
  certbot-etc:
  certbot-var:

networks:
  app-network:
    driver: bridge
