version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - TZ=Asia/Yekaterinburg
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf
      - ./index.html:/usr/local/sbin/nginx-proxy/html/index.html
      - ./nginx-logs:/usr/local/sbin/nginx-proxy/log
      - ./certbot-data/conf:/etc/letsencrypt
      - ./certbot-data/www:/var/www/certbot
    ports:
      - "80:50080"
      - "443:50443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot-data/conf:/etc/letsencrypt
      - ./certbot-data/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
